services:

  db:
    container_name: dbcloud_storage
    image: postgres:16.0-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    env_file:
      - ./cloud_storage/.env

  redis:
    container_name: redis
    image: redis:latest
    command: >
      sh -c '
        mkdir -p /usr/local/etc/redis &&
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
        echo "requirepass $REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
        echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
        redis-server /usr/local/etc/redis/redis.conf
      '
    ports:
      - 6380:6379
    env_file:
      - ./cloud_storage/.env

volumes:
  postgres_volume: